services:
  backend:
    build:
      context: .
      dockerfile: devops/backend/Dockerfile.prod
    container_name: wick-backend
    ports:
      - "3001:3001"
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--dns-result-order=ipv4first"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: devops/frontend/Dockerfile.prod
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
    container_name: wick-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: wick-prod-network
