services:
  backend:
    build:
      context: .
      dockerfile: devops/backend/Dockerfile.prod
    container_name: qpbd-backend
    ports:
      - "3001:3001"
    env_file:
      - apps/backend/.env.prod
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--dns-result-order=ipv4first"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: devops/frontend/Dockerfile.prod
    container_name: qpbd-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: qpbd-prod-network
